#!/usr/bin/env python3

# Usage example: clean-csv domain < input.csv | tr -d '"' | tail -n+2 | top-tlds --limit 10 | jq
# TODO: Add "skip header" option to clean-csv to avoid the need for tail -n+2

import sys
import collections
import argparse
import json


def main():
    parser = argparse.ArgumentParser()

    group = parser.add_mutually_exclusive_group(required=True)

    group.add_argument("-c", "--coverage", type=float)
    group.add_argument("-l", "--limit", type=int)

    args = parser.parse_args()

    c = collections.Counter()
    hosts = 0

    for line in sys.stdin:
        hosts += 1
        line = line.strip()
        tld = line.split(".")[-1]
        c[tld] += 1

    coverage = 0
    result_count = 0

    results = {}

    for tld, count in c.most_common():
        if args.limit and result_count >= args.limit:
            break

        if args.coverage and coverage >= args.coverage:
            break

        percentage = count / hosts
        coverage += percentage
        result_count += 1

        results[tld] = {}
        results[tld]["count"] = count
        results[tld]["percentage"] = percentage

    results["coverage"] = coverage
    results["count"] = result_count

    print(json.dumps(results))


if __name__ == "__main__":
    main()
